name: Deploy React App to GitHub Pages

# Dispara o fluxo de trabalho quando houver push na branch main ou manualmente
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código do repositório
      - name: Checkout repository content
        uses: actions/checkout@v4

      # Passo 2: Configura o Node.js na versão correta
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Passo 3: Instala as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Passo 4: Gera o build de produção
      - name: Build the project
        run: npm run build

      # Passo 5: Faz o deploy no GitHub Pages usando o gh-pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
