name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Altere se sua branch principal for outra, como master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Configuração do Node.js (altere a versão conforme necessário)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instala as dependências do projeto
      - name: Install dependencies
        run: npm install

      # Executa o build do projeto
      - name: Build the project
        run: npm run build  # Altere conforme o comando de build do seu projeto

      # Faz o deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Altere conforme o diretório de saída do build
