name: React CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Altere para a versão do Node.js que você está utilizando

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watchAll=false # Executa os testes do React

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
